-- Admin wallet management: the wallet ledger, and admin-facing search,
-- detail, transaction history, and manual adjustment functions.
--
-- The wallet and wallet_transactions tables are created here idempotently
-- because they may already exist from the server repo's own migration
-- (same Supabase project, two repos tracking migrations independently). This
-- file is safe to run whether or not that one has been applied.
--
-- As with admin_user_management.sql, every admin-facing function re-checks
-- authorisation itself (is_admin() or is_service_role()) rather than trusting
-- the caller, and reads/writes go through SECURITY DEFINER functions rather
-- than a new RLS policy — a wallet is not a profile, but the shape of "an
-- administrator needs to see every row" is the same problem already solved
-- there.

-- Ledger --------------------------------------------------------------------

create table if not exists public.wallets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  available_balance_cents bigint not null default 0 check (available_balance_cents >= 0),
  held_balance_cents bigint not null default 0 check (held_balance_cents >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.wallets is
  'One row per member. Total balance is available_balance_cents + held_balance_cents, computed on read rather than stored.';

create table if not exists public.wallet_transactions (
  id uuid primary key default gen_random_uuid(),
  wallet_id uuid not null references public.wallets(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('TOPUP','ESCROW_HOLD','ESCROW_RELEASE','WITHDRAWAL','REFUND')),
  amount_cents bigint not null,
  description text not null,
  status text not null check (status in ('PENDING','COMPLETED','FAILED','REFUNDED')),
  stripe_payment_intent_id text unique,
  stripe_event_id text unique,
  currency text not null default 'sgd',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.wallet_transactions is
  'Append-only ledger. amount_cents is signed: positive for credits, negative for debits. A correction is a new row, never an edit to an existing one.';

create index if not exists wallet_transactions_wallet_id_idx
  on public.wallet_transactions (wallet_id, created_at desc);

alter table public.wallets enable row level security;
alter table public.wallet_transactions enable row level security;

drop policy if exists "users read own wallet" on public.wallets;
create policy "users read own wallet"
  on public.wallets for select
  using (auth.uid() = user_id);

drop policy if exists "users read own transactions" on public.wallet_transactions;
create policy "users read own transactions"
  on public.wallet_transactions for select
  using (auth.uid() = user_id);

-- Two more transaction types, for a manual correction an administrator makes
-- directly against a wallet rather than one generated by top-up, escrow, or
-- withdrawal flows.
alter table public.wallet_transactions drop constraint if exists wallet_transactions_type_check;
alter table public.wallet_transactions add constraint wallet_transactions_type_check
  check (type in ('TOPUP','ESCROW_HOLD','ESCROW_RELEASE','WITHDRAWAL','REFUND','ADMIN_CREDIT','ADMIN_DEBIT'));

-- Wallet lookup ---------------------------------------------------------

/**
 * Searches wallets by the owner's display name, email address, account id,
 * or the wallet's own id.
 *
 * strpos rather than LIKE for the same reason as admin_search_users: '%' and
 * '_' typed into the search box should match literally, not act as wildcards.
 */
create function public.admin_search_wallets(
  search text default '',
  result_limit int default 25,
  result_offset int default 0
)
returns table (
  id uuid,
  user_id uuid,
  email text,
  display_name text,
  available_balance_cents bigint,
  held_balance_cents bigint,
  created_at timestamptz,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  needle text := lower(trim(coalesce(search, '')));
begin
  if not (public.is_admin() or public.is_service_role()) then
    raise exception 'Not authorised' using errcode = '42501';
  end if;

  return query
    select
      w.id,
      w.user_id,
      u.email::text,
      p.display_name,
      w.available_balance_cents,
      w.held_balance_cents,
      w.created_at,
      count(*) over () as total_count
    from public.wallets w
    join auth.users u on u.id = w.user_id
    left join public.profiles p on p.id = u.id
    where
      needle = ''
      or strpos(lower(coalesce(u.email::text, '')), needle) > 0
      or strpos(lower(coalesce(p.display_name, '')), needle) > 0
      or strpos(lower(u.id::text), needle) > 0
      or strpos(lower(w.id::text), needle) > 0
    order by w.created_at desc
    limit least(greatest(result_limit, 1), 100)
    offset greatest(result_offset, 0);
end;
$$;

/** One wallet by id, or no rows when it does not exist. */
create function public.admin_get_wallet(target_wallet_id uuid)
returns table (
  id uuid,
  user_id uuid,
  email text,
  display_name text,
  available_balance_cents bigint,
  held_balance_cents bigint,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not (public.is_admin() or public.is_service_role()) then
    raise exception 'Not authorised' using errcode = '42501';
  end if;

  return query
    select
      w.id,
      w.user_id,
      u.email::text,
      p.display_name,
      w.available_balance_cents,
      w.held_balance_cents,
      w.created_at
    from public.wallets w
    join auth.users u on u.id = w.user_id
    left join public.profiles p on p.id = u.id
    where w.id = target_wallet_id;
end;
$$;

/**
 * One wallet's transaction history, newest first.
 *
 * metadata rides along unfiltered: some rows carry a booking reference there
 * (there is no dedicated column for one yet), and the caller decides whether
 * to show it.
 */
create function public.admin_get_wallet_transactions(
  target_wallet_id uuid,
  result_limit int default 25,
  result_offset int default 0
)
returns table (
  id uuid,
  type text,
  amount_cents bigint,
  description text,
  status text,
  currency text,
  metadata jsonb,
  created_at timestamptz,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not (public.is_admin() or public.is_service_role()) then
    raise exception 'Not authorised' using errcode = '42501';
  end if;

  return query
    select
      t.id,
      t.type,
      t.amount_cents,
      t.description,
      t.status,
      t.currency,
      t.metadata,
      t.created_at,
      count(*) over () as total_count
    from public.wallet_transactions t
    where t.wallet_id = target_wallet_id
    order by t.created_at desc
    limit least(greatest(result_limit, 1), 100)
    offset greatest(result_offset, 0);
end;
$$;

-- Manual adjustment -------------------------------------------------------

/**
 * Applies a manual credit or debit to a wallet.
 *
 * amount_cents is always the positive amount an administrator typed; the
 * signed ledger amount is derived here so it matches the convention every
 * other transaction already uses (positive for a credit, negative for a
 * debit). Everything happens in one transaction: the wallet row is locked
 * before its balance is checked, so a concurrent adjustment cannot race past
 * the available-balance check, and any validation failure raises before the
 * insert or update runs, leaving the wallet untouched.
 *
 * Writes a new ledger row rather than touching an existing one, and records
 * the action through record_admin_action rather than inserting into
 * admin_audit_log directly, so wallet adjustments show up in the same audit
 * trail as every other administrator action, attributed the same way.
 */
create function public.admin_apply_wallet_adjustment(
  target_wallet_id uuid,
  direction text,
  amount_cents bigint,
  reason text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  w public.wallets%rowtype;
  signed_amount bigint;
  new_transaction_id uuid;
  previous_balance bigint;
  updated_balance bigint;
begin
  if not (public.is_admin() or public.is_service_role()) then
    raise exception 'Not authorised' using errcode = '42501';
  end if;

  if direction not in ('CREDIT', 'DEBIT') then
    raise exception 'Direction must be CREDIT or DEBIT';
  end if;

  if amount_cents is null or amount_cents <= 0 then
    raise exception 'Amount must be greater than zero';
  end if;

  if trim(coalesce(reason, '')) = '' then
    raise exception 'A justification is required';
  end if;

  select * into w from public.wallets where id = target_wallet_id for update;
  if not found then
    raise exception 'Wallet not found';
  end if;

  if direction = 'DEBIT' and amount_cents > w.available_balance_cents then
    raise exception 'Amount exceeds available balance';
  end if;

  signed_amount := case direction when 'CREDIT' then amount_cents else -amount_cents end;
  previous_balance := w.available_balance_cents;
  updated_balance := previous_balance + signed_amount;

  insert into public.wallet_transactions (wallet_id, user_id, type, amount_cents, description, status, currency)
  values (
    w.id,
    w.user_id,
    case direction when 'CREDIT' then 'ADMIN_CREDIT' else 'ADMIN_DEBIT' end,
    signed_amount,
    reason,
    'COMPLETED',
    'sgd'
  )
  returning id into new_transaction_id;

  update public.wallets
  set available_balance_cents = updated_balance, updated_at = now()
  where id = w.id;

  perform public.record_admin_action(
    case direction when 'CREDIT' then 'wallet_credit_applied' else 'wallet_debit_applied' end,
    w.user_id,
    jsonb_build_object(
      'wallet_id', w.id,
      'transaction_id', new_transaction_id,
      'direction', direction,
      'amount_cents', amount_cents,
      'reason', reason,
      'previous_balance_cents', previous_balance,
      'updated_balance_cents', updated_balance
    )
  );

  return new_transaction_id;
end;
$$;

-- Execution rights -----------------------------------------------------------

revoke execute on function public.admin_search_wallets(text, int, int) from public, anon;
revoke execute on function public.admin_get_wallet(uuid) from public, anon;
revoke execute on function public.admin_get_wallet_transactions(uuid, int, int) from public, anon;
revoke execute on function public.admin_apply_wallet_adjustment(uuid, text, bigint, text) from public, anon;

grant execute on function public.admin_search_wallets(text, int, int) to authenticated, service_role;
grant execute on function public.admin_get_wallet(uuid) to authenticated, service_role;
grant execute on function public.admin_get_wallet_transactions(uuid, int, int) to authenticated, service_role;
grant execute on function public.admin_apply_wallet_adjustment(uuid, text, bigint, text) to authenticated, service_role;
